### ISSUE TITLE
Read date format DD.MM.YYYY

### ISSUE THREAD

**Issue by simakovpa** [pyrochlore/obsidian-tracker#10]
Need to understand the format of date: DD.MM.YYYY

Now it shows this:

![image](https://user-images.githubusercontent.com/18704269/116576160-82587f80-a939-11eb-9e70-4062c7fbf00c.png)

**Comment by pyrochlore** [comment]
Hi, the parameters startDate and endDate should also match your dateFormat “DD.MM.YYYY”.

**Comment by pyrochlore** [comment]
Hi, 
The issue had been [tested](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestDateFormats.md) and seems ok.
I will close the issue. If you still have problems using it, you can reopen this issue and ask questions.
