### ISSUE TITLE
Line color always black. 

### ISSUE THREAD

**Issue by Almadual** [pyrochlore/obsidian-tracker#101]
So I am trying to build a habit tracker into my daly notes. Problem is, the lines are not outputing the color I specify in the attribute. I am pretty new to programming anything, so if this is very obvious im sorry. 

![image](https://user-images.githubusercontent.com/96316790/146607242-69ea6adf-f18a-4715-82a0-ddc845886c7c.png)

**Comment by pyrochlore** [comment]
Hi,

I did a simple test but not getting the line color problem.
Here is the settings I have.
![image](https://user-images.githubusercontent.com/3617615/155636734-5fbfcbd3-0166-4460-969e-1a48f7a43d19.png)

Notice that the regular expression for "Sleep" in your example will also match the data from "gSleep", so I added a "^" to force it match only the line starts with "Sleep".

If you still have problem with line color, you can send me  a packed example to me as attachments, then I can check it for you.

**Comment by pyrochlore** [comment]
Will close issue, welcome to reopen it if you still have problems with it.
