### ISSUE TITLE
Multiple Hex Color codes create an error

### ISSUE THREAD

**Issue by blackpeasy** [pyrochlore/obsidian-tracker#104]
I like coloring my trackers with Hex codes to create more pleasing colors. However, multiple hex codes seem to break the plugin.

Works:
```lineColor: red, blue, green```

Doesn't work:
```lineColor: "#e35259", "#22b4b7", "#96c8a2"```

**Comment by pyrochlore** [comment]
Please try this

```
    lineColor: "#e35259, #22b4b7, #96c8a2"
```
or
```
    lineColor: ["#e35259", "#22b4b7", "#96c8a2"]
```

**Comment by pyrochlore** [comment]
Will close this issue, welcome to reopen it if you still have problems with it.
