### ISSUE TITLE
Error parsing YAML encountered (already read FAQ)

### ISSUE THREAD

**Issue by ztlee042** [pyrochlore/obsidian-tracker#107]
Hi, 

First of all, thanks for developing this tool!

I have some frontmatter fields on my tasks page to track time, like:

```
start_time: 15:10:42
end_time: 15:18:45
duration: 0:08:03
```

Then I am trying to get these data via tracker, then I constantly get `Error parsing YAML` problem:

```tracker
searchType: dvField
searchTarget: 'duration'
folder: "04 Log/04_Task/Test" 
endDate: 2021-01-06
xDataset: 0 
summary: 
	template: 'Total hours spent: {{sum()}} hours'
```

I could not figure out what's going on, could you help me? 
Many thanks!

**Comment by tamvodopad** [comment]
@ztlee042 this problem in obisdian yamp parser.  Replacing all the tabs in the code block with single spaces fixed everything.

more about problem - https://forum.obsidian.md/t/bug-tracker-plugin-yaml-errors-on-ipados/27793/3

**Comment by ztlee042** [comment]
@tamvodopad 
Thanks for the help! The YAML parser problem was solved!
