### ISSUE TITLE
Trying for a sum of pages in book counter: Various questions

### ISSUE THREAD

**Issue by ReaderGuy42** [pyrochlore/obsidian-tracker#109]
I'm trying to implement a chart that shows the overall pages I've read in a book tracker, I "made". I have a bunch of things in the frontmatter for the notes:

```
Author: 
Title: 
Year: 
Medium: 
CurrentPage: 
TotalPages: 
Status: 
Rating: 
DateStarted: <% tp.date.now() %>
DateFinished: 
Cover: 
```
Of importance for here is the "TotalPages", which I'm trying to have it add up. I've tried the following Tracker code blocks, but both get me the same error: "No valid date as X value found in notes 12 files are not in the right format."
``` tracker
searchType: frontmatter
searchTarget: TotalPages
folder: /Log
startDate:
endDate:
summary:
    template: "Total amount of pages read is {{sum}}"
    style: "color:white;"
```

``` tracker
searchType: frontmatter
searchTarget: TotalPages
folder: /Log
startDate:
endDate:
bar:
    title: "Bar Chart"
    xAxisLabel: Date
    yAxisLabel: Value
```

Any ideas? Thanks!

**Comment by ReaderGuy42** [comment]
Ok, so I figured that out, by adding the `xDataset: 0`, telling it to look for the date in the front matter. The issue was that it was looking for a date in the note title. I do have another question: How can I tell it, to only use notes that have a specific frontmatter with a particular value? So for me that'd be "Medium: Book", to differentiate from audiobooks, whose "page numbers" (hours) would confuse the whole thing. 
In the Dataview plugin, you can tell it something like `WHERE Medium = "Book"`

**Comment by ReaderGuy42** [comment]
Ok, I figured the filtering thing out too, for now. I just gave the audiobook metadata another name for that variable (TotalLength, instead of TotalPages), which solves that bit. 
Another question now is if there's a way to have the diagrams graph things additively? By this I mean that Instead of having the line in the graph go up and down it would only go up. E.g. if Book 1 has 200 pages and I finish that on January 1, and Book 2 has 100 pages and I finish that the next week, instead of the line going DOWN to 100, the second value of the graph would go UP to 300 since the overall number of pages is now 300. Is this possible?
Thanks :)

**Comment by ReaderGuy42** [comment]
I figured that out too, by adding `accum: true` to the code block. Two other questions have since popped up: How can I have a summary tracker act as a counter? 

Meaning, how can I have it show a number of the total entries in a certain table, for example. I've solved this by adding a new thing in the frontmatter `BookCounter: 1` and having a Summary Tracker add those together. 

This works (even though my frontmatter is starting to be a little cluttered), but brings me to my other question: How do I disable the "fractional" sum? So for this I don't need the `.0` after the number of books read, since I only count finished books, not fractional ones. 
Is it possible to remove the period and the 0?
Thanks :)

**Comment by pyrochlore** [comment]
Hi, sorry for the late response, I had hard time working these days.
Really appreciate your trying.

Back to the problem,
```
bar:
    ...
    yAxisLabel: "My Label"
    ...
```
should do the work.

If you still have that problem, you can send me a simplified example here then I can check it for you.

**Comment by ReaderGuy42** [comment]
The number after the period/comma. So like I have a front matter variable called "TotalPages", e.g. `TotalPages: 123`, but if I have your plugin add this variable with the ones from other notes I always get a number like this: 123.**0**. It's always `0` since I don't enter a fractional (partial) page :)

**Comment by pyrochlore** [comment]
Please use "{{sum()::i}}" in template to force the output formatted in integer

**Comment by ReaderGuy42** [comment]
Perfect! Thank you!!

**Comment by ReaderGuy42** [comment]
One last thing, I'm trying to create a graph that shows the publication years of the books, with the front matter variable `year: ...` so it would look something like this example from Goodreads:
![image](https://user-images.githubusercontent.com/71895400/155683630-346396fe-0b0f-4e60-b4ff-98cf403cc403.png)

My tracker code block looks like this:
``` tracker
searchType: frontmatter
searchTarget: DateFinished, Year
xDataset: 0
folder: /Log/2022
accum: false
startDate: 2022-01-01
endDate:
line:
    title: "Line Chart"
    xAxisLabel: Date
    yAxisLabel: Year
    fillGap: false
```
And even though I have the `fillGap: false` in there, it ends up adding up some of the values and ends up looking like this:
![image](https://user-images.githubusercontent.com/71895400/155683770-23de99c4-6434-4f99-a833-0eda49734cdc.png)

I would like to just have the years charted on the y axis, and not have the value of the year added up, which is happening here. Is this possible with Tracker?
Thanks!

**Comment by pyrochlore** [comment]
Tracker will connect adjacent dots, assign fillGap to true force it to connect dots even data missing between two dots.
You can use set showLine to false to hide lines.

For the date format on x axis, set xAxisTickLabelFormat to YYYY, and xAxisTickInterval to 1y

```
......
line:
    showLine: false
    xAxisTickLabelFormat: YYYY
    xAxisTickInterval: 1y
```

**Comment by ReaderGuy42** [comment]
Thanks, that gave me a `YAML Error` and now I just updated to the most current version of the plugin and now nothing works, i.e. the space where the tracker block should be is just blank?

**Comment by pyrochlore** [comment]
Mm…. do you have any tabs in the YAML block?
Now they will be replaced by spaces (by default 4 spaces)

**Comment by ReaderGuy42** [comment]
I don't think so. The graphs sometimes (don't know why but not always) work but the summary trackers don't. Here's a example vault, with the basic structure at front matter
[tracker-test.zip](https://github.com/pyrochlore/obsidian-tracker/files/8141058/tracker-test.zip)

**Comment by pyrochlore** [comment]
I didn't get `YAML erros` from the example you provided.
The texts from summary output are cropped, will check it.

**Comment by ReaderGuy42** [comment]
That seems to work again, thanks!
