### ISSUE TITLE
Tracker not rendering

### ISSUE THREAD

**Issue by lillianhorin** [pyrochlore/obsidian-tracker#110]
Hey! I'm very excited to use this plugin. Just haven't had much luck getting it to work. I'm trying to render a simple calendar that tracks instances of task Exercise being done. But nothing shows up in preview, and I'm not getting any error messages. It just doesn't render at all.

Thanks for your help!
![image](https://user-images.githubusercontent.com/24489520/151020811-b46e62f1-c9d8-48f6-aa0f-cab496ff5111.png)

**Comment by pyrochlore** [comment]
Hi, here is an example how you can track task done.

![image](https://user-images.githubusercontent.com/3617615/155319539-62935cb7-2336-4c3c-a5fd-673a5ca6614d.png)

Notice currently wiki links are not allowed.

**Comment by pyrochlore** [comment]
Will close this issue. You can reopen it if you still have problems with it.
