### ISSUE TITLE
[QUESTION] Is it possible use regular expressions in the file field value?

### ISSUE THREAD

**Issue by 4174** [pyrochlore/obsidian-tracker#115]
Hey! Sorry, but I did not find how to use regular expressions in the file field value. Is it possible?

**Comment by pyrochlore** [comment]
Regular expressions in the file field are not supported now. 
But you can assign multiple files if there are not too many of them. 
XD

**Comment by 4174** [comment]
Thanks. In my case, when I use a tracker inside a daily note template, I found that the following format could be used: {{date}}.
