### ISSUE TITLE
[FEATURE REQUEST] Not Number Treshold in Month view

### ISSUE THREAD

**Issue by AtlcatlQ** [pyrochlore/obsidian-tracker#116]
I'm trying to use this plugin for a habit tracker but for "Boolean Habits", habits that are done, or aren't. But I dont find a way to use it to make the day in the month view to be marked. Is there a way to do it?

if there aren't I would be grateful if you make this a feature.

(sorry for the bad english)

**Comment by pyrochlore** [comment]
You can use tasks (e.g. - [ ] habit) in your daily notes and track them using `searchType` task.done.

Example trackers are [here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTask.md)

**Comment by pyrochlore** [comment]
Will close this issue, you can reopen it if you still get problems with it.
