### ISSUE TITLE
about tags

### ISSUE THREAD

**Issue by johnsonsuqs** [pyrochlore/obsidian-tracker#117]
#tag1/tag2  
#tag1/tag3

searchType tag
searchTarget：#tag1,#tag1/tag3
---
I suggest  tag in level 1(#tag1) can be summed   ,now only   level 2 (#tag1/tag2 or #tag1/tag3) can be

**Comment by pyrochlore** [comment]
It already did what you said.
Please check the following example
![image](https://user-images.githubusercontent.com/3617615/156136988-c824a573-f4cc-4133-b76f-d8274f64dff3.png)

**Comment by johnsonsuqs** [comment]
thank for  your reply. what I want to say:  
 searchtype tag
searchtype tag1,tag1/tag2,tag1/tag3
pie
....
data:`{{sum(dataset(0))}},{{sum(dataset(1))}},{{sum(dataset(2))}}`
....
I try many times ,I found I can`t sum tag1,

**Comment by pyrochlore** [comment]
Hi @johnsonsuqs,
Here is an example showing the usage
![image](https://user-images.githubusercontent.com/3617615/156274814-71c72b5e-ab80-46e8-bee6-02f180b27350.png)

**Comment by pyrochlore** [comment]
Will close this issue. If you still have problems with it, welcome to reopen it.

**Comment by SalahAdDin** [comment]
It seems tracker does not work with such nested tags.
