### ISSUE TITLE
Summary rendering overlaps chart (v1.10.9)

### ISSUE THREAD

**Issue by robosquiggles** [pyrochlore/obsidian-tracker#119]
I just updated to version 1.10.19, and the rendering of my bullet charts has changed. They showed up fine before, with the summary appearing above the chart. Please see the images below.

![image](https://user-images.githubusercontent.com/8586879/156859698-7a609728-c12c-4800-8933-1b4146f4b4f2.png)
![image](https://user-images.githubusercontent.com/8586879/156859723-d2d3d56b-1112-4ab8-a84b-1359c07f9466.png)

This seems to be the case only on my Mac OS and Windows machine(s). Android seem to render properly. I don't have an iOS device to test on.

I wonder if this is an issue with my theme or some interference with another plugin? Let me know if I need to provide additional information to help replicate or debug this. Thanks!

**Comment by robosquiggles** [comment]
Also, I just want to say that I am a huge fan of this plugin! I appreciate all the work you do for the community! 🙇‍♀️

**Comment by pyrochlore** [comment]
Will have a check on this issue.

**Comment by pyrochlore** [comment]
Hi @robosquiggles, 
Could you try reinstall the plugin (uninstall and install again).
Looks like there are some glitching in the previous pushed code.

The current code on my side looks ok without overlapping.

![image](https://user-images.githubusercontent.com/3617615/156991180-d1c01fca-1ec3-4c9d-800b-985694552f2a.png)
