### ISSUE TITLE
Legend Not Showing

### ISSUE THREAD

**Issue by shawnduggan** [pyrochlore/obsidian-tracker#12]
This is an awesome plugin, but I am having trouble getting the legend to render. I followed the example in TestLegends.md.

```tracker
searchType: frontmatter
searchTarget: sleep, mood, energy, productivity
folder: Daily Notes
startDate: 2021-05-02
endDate: 2021-05-08
line:
    title: Trackers
    yAxisLabel: Sleep, Mood, Energy, Productivity
    yAxisUnit: Hours
    showPoint: true
    lineColor: black, green, red, blue
    showLegend: true
    legendPosition: right
    legendOrientation: horizontal
```
<img width="679" alt="Screen Shot 2021-05-05 at 8 59 07 PM" src="https://user-images.githubusercontent.com/3504807/117223764-c093ea00-ade4-11eb-9525-f6955c596444.png">

**Comment by pyrochlore** [comment]
Thanks for the feedback.
The yAxisLabel only accepts two values, for the left y-axis and right y-axis.
That might be the source of problem.
I will refine the error handling and message in the next release.

Also, if you want to apply a set the label in legend for datasets, use the parameter datasetName.
Here are the [example](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/BloodPressureTracker.md).

**Comment by shawnduggan** [comment]
Thanks for your reply - I corrected my issue.
