### ISSUE TITLE
custom delimiter for multiple values 

### ISSUE THREAD

**Issue by scorius13** [pyrochlore/obsidian-tracker#13]
Thanks for this plugin! It is very handy for visualization. I wonder if you would consider adding an option to customize delimiters in content with multiple values.

Currently the delimiter is '/', so for example, I can search for sleep[0] and sleep[1] in the frontmatter content below: 
```
---
sleep: 180/120
---
```

It would be great if we can set our own delimiter, such as "," or ";", so I can write:
```
---
sleep: [180, 120]
---
```

This will allow more flexibility and also compatibility with other uses (e.g. arrays in the Dataview plugin). Thank you!

**Comment by pyrochlore** [comment]
> This will allow more flexibility and also compatibility with other uses (e.g. arrays in the Dataview plugin)
Good point to me. I will add this after the next release.

**Comment by scorius13** [comment]
> That's a good point to me. I will add this after the next release.

Thank a ton! Looking forward to it.

> By the way, do you really need a separator like ';'?
> Or the YAML array format [X, Y, ....] is enough?

No not really. `[X, Y, ....]` is perfectly fine :)

**Comment by pyrochlore** [comment]
Will close this issue.
Any further questions and feature requests are still welcome.
