### ISSUE TITLE
Possible to track text::variable like dataview does?

### ISSUE THREAD

**Issue by Quorafind** [pyrochlore/obsidian-tracker#16]
It will be nice for me that I use same data in same format

**Comment by pyrochlore** [comment]
You can use this to track "target:: variable"
```
searchType: text
searchTarget: 'target::\\s+(?<value>[\\-]?[0-9]+[\\.][0-9]+|[\\-]?[0-9]+)'
line:
    title: Test
```

**Comment by pyrochlore** [comment]
Do you think it’s necessary to add a new search type ‘dataview’ to search this kind of pattern?

**Comment by Quorafind** [comment]
@pyrochlore I am finding a good way to combine tracker and dataview, it might be nice to make tracker works with dataview more closely?

**Comment by Quorafind** [comment]
But your solution is good enough, so it depends on if it is difficult to add a new tracker pattern

**Comment by pyrochlore** [comment]
It's not that hard. 
Since other people are also asking this feature.
I will consider add this in the future release.

Thanks for the feedback.

**Comment by pyrochlore** [comment]
A new searchType 'dvField' has been added to dev branch for this case.
It will be released in the next version.

**Comment by pyrochlore** [comment]
Version 1.5.0 just released. 
You can find examples of the new searchType 'dvField' [here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestMultipleTargesMultipleValues.md#multiple-values-in-dvfield-dataview-inline-field).

**Comment by pyrochlore** [comment]
Will close this issue.
Issues and feature requests are still welcome.
