### ISSUE TITLE
bullet chart customization

### ISSUE THREAD

**Issue by jschroeder7** [pyrochlore/obsidian-tracker#165]
What other values can we use to customize the bullet chart?

**Comment by jschroeder7** [comment]
![1](https://user-images.githubusercontent.com/99705212/189488863-7f2dcadf-7d97-428a-97ec-f6983e14b278.jpg)
![2](https://user-images.githubusercontent.com/99705212/189488868-722fcf06-758c-46af-8055-1b9a9af6452a.jpg)
![3](https://user-images.githubusercontent.com/99705212/189488870-0eb0f3f9-4307-442d-8825-1c160ff17253.jpg)
![4](https://user-images.githubusercontent.com/99705212/189488876-8f190d6e-31bc-42cf-b8a0-a14c3426065f.jpg)

**Comment by jschroeder7** [comment]
I attached some screenshots, would be cool to figure out what I am doing wrong, trying to display the vertical bullet graph.

@pyrochlore

**Comment by jschroeder7** [comment]
![5](https://user-images.githubusercontent.com/99705212/189489005-4c3af39a-b59b-4c50-8061-f5460a1b73e5.jpg)
![6](https://user-images.githubusercontent.com/99705212/189489033-f172c493-9c1b-4366-a761-4bce16a9ddb2.jpg)

**Comment by jebeaudoin** [comment]
Is it possible to expand the length (if horizontally oriented) of the bullet chart?
