### ISSUE TITLE
Possible to track data in table rows

### ISSUE THREAD

**Issue by danraymond** [pyrochlore/obsidian-tracker#17]
As I mentioned in the Discord; would be nice if I could track and graph rows (say in a table) like date: 2021-03-04 time: 5:45 systolic: 125 diastolic 65. I can make a table nicely using dataview it would be amazing if they could play together!

**Comment by pyrochlore** [comment]
Is the table you mentioned generated from dateview plugin or a pure text markdown table?
If it is from dataview, what is the data source of it?

**Comment by danraymond** [comment]
it's a markdown table almost always as its external data being recorded to
a single file not the result of a search. E.g. accumulated  blood pressure
for one person.

I sometimes use a data view to pull data from the vault, but it's not a
real table but a temporary generated view I thought?

**Comment by pyrochlore** [comment]
I am working on table values extraction for the next version (1.5). 
Then time values will be in version 1.6.
After that, it should be able to fit your request.

**Comment by danraymond** [comment]
Oh man!So clever, thank you!DanSent via the Samsung Galaxy Note9, an AT&T 4G LTE smartphone
-------- Original message --------From: pyrochlore ***@***.***> Date: 5/17/21  17:10  (GMT+10:00) To: pyrochlore/obsidian-tracker ***@***.***> Cc: danraymond ***@***.***>, Author ***@***.***> Subject: Re: [pyrochlore/obsidian-tracker] Possible to track data in table rows (#17) 
I am working on table values extraction for the next version (1.5).
Then time values will be in version 1.6.
After that, it should be able to fit your request.

**Comment by pyrochlore** [comment]
Version 1.5.0 just released with table values extraction.
[Here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTable.md) is an example of it.
The feature of time values will be in the next release (v1.6.0).

**Comment by pyrochlore** [comment]
Will close this issue first for the table feature.
Time values feature is in development.
