### ISSUE TITLE
Rolling date range?

### ISSUE THREAD

**Issue by michaelpporter** [pyrochlore/obsidian-tracker#170]
Is there a way to get have a tracker view of the last X days? i.e. I line graph of minutes of exercise per day in the last 30 days.

**Comment by marcomusso** [comment]
See https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestDateFormats.md#relative-date-input-for-startdate-and-enddate, I'm using `startDate: -1y` and `endDate: 0d` to show a rolling "last year" for example.

**Comment by michaelpporter** [comment]
Perfect, thanks.
