### ISSUE TITLE
Limit time range dynamically

### ISSUE THREAD

**Issue by flip-md** [pyrochlore/obsidian-tracker#18]
Heyhey, let me first say I love your plugin!

I'd really like to generate a graph that only shows the last n entries, is there any chance you could add something like

```
...
startDate: -n
```
?

Cheers

**Comment by pyrochlore** [comment]
Great idea.
It would be very helpful if one wants to track, for example, the data in last month.
With this, no need to change the startDate every time one opens the tracker file.

**Comment by eatondpe** [comment]
This might do what I want. More specifically, I'd like to include natural language dates so that dynamically I can have Tracker show me data that meets these criteria. (Any form of date math for date ranges would work.) Possible?

``` tracker
searchType: frontmatter
searchTarget: Sleep
folder: Journal/
startDate: one month ago
endDate: 
line:
    title: "Sleep"
    xAxisLabel: Date
    yAxisLabel: Value
```

**Comment by pyrochlore** [comment]
Hi @eatondpe,
  Do you use the plugin [nldates-obsidian](https://github.com/argenos/nldates-obsidian)?
  I am considering using the API it provides to help parsing natural language dates, but that will require users to install the plugin to use it.

**Comment by eatondpe** [comment]
Yes. I do use the nldates plug-in. I need it for a few other plug-ins, too.

**Comment by pyrochlore** [comment]
Thanks @eatondpe .
I will do more research and implement the feature.

**Comment by pyrochlore** [comment]
Hi @eatondpe,

I have to apologize for the promise to you.
Regarding to the frequency of writing date fields in tracker code block, and the complexity of using/mixing natural language dates (NLD) with momentjs dates,  I decided not to use NLD for the date input.

To input a relative date to today, 
I might use "-1d", "-3w", "-5m", "-1y" where d/w/m/y stands for day/week/moth/year.

**Comment by eatondpe** [comment]
No worries. Your suggestion would work just as well. Maybe even better!

**Comment by pyrochlore** [comment]
The feature was just released with version 1.8.0.
[Here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestDateFormats.md#relative-date-input-for-startdate-and-enddate) is an example

**Comment by eatondpe** [comment]
Works beautifully! Thanks!

**Comment by pyrochlore** [comment]
Will close the issue.
Welcome to report more bugs or make suggestions.
