### ISSUE TITLE
Cannot register pages in specified folder

### ISSUE THREAD

**Issue by Lennon-ruthven** [pyrochlore/obsidian-tracker#20]
Hello, I am unsure why this problem exists.

my code is:

```tracker
searchTarget: Learn, Improve my wellbeing, Make progress, Manage my energy, Be mindful, Contribute, Share, Strive, Love my family, Love myself
searchType: dvField
datasetName: 👩‍🎓 Learning, 👩 Wellbeing, 📈 Progress, 💡 Energy, 🌸Mindfulness, 🎁 Contribute, 📬 Share, 💯 Strive, 💕 Family, 💜 Self-love
folder: + Day Notes
startDate: 2021-05-15
fitPanelWidth: true
line:
    title: Daily Questions Summary
    lineColor: magenta, red, orange, green, cyan, blue, purple, indigo, black, grey
    showLegend: true
    legendPosition: right
    yMax: 10
```

I am trying to achieve this so my data is read from a Day Note and translated across to the tracker. 

The section in my day note looks like this:

    - #❓/👩‍🎓 | Learn:: 1
    - #❓/👩 | Improve my wellbeing::  2
    - #❓/📈 | Make progress:: 3
    - #❓/💡 | Manage my energy:: 4 
    - #❓/🌸 | Be mindful:: 4
    - #❓/🎁 | Contribute:: 5
    - #❓/📬 | Share:: 6
    - #❓/💯 | Strive:: 7
    - #❓/💕 | Love my family:: 7 
    - #❓/💜 | Love myself:: 8

I create pages in the specified day note folder, shown on line 7 in the Tracker Example, using the data from my Day Note just above, yet i receive this: https://gyazo.com/5dfea46876248dacb4ea349b5ae87357

Sorry for your time, I just have no idea what I'm doing wrong.

**Comment by pyrochlore** [comment]
It's ok to ask me any question about the plugin.

I am not sure what exactly happen in your vault.
Maybe your notes does not exist in the folder? 
or the date format of the note does not match the settings?

I copied your data above and made a test project [here](https://drive.google.com/file/d/1a-SIeAC6xjca-YxdG8zJIkoL5nJFpp33/view?usp=sharing) like this.
![image](https://user-images.githubusercontent.com/3617615/119230410-a2511c80-bb4e-11eb-9ec2-e7394b9c33d8.png)

Please put the folder 'case' under your vault to see the result and do some comparison.

**Comment by pyrochlore** [comment]
Will close this issue.
If you still have problem using the plugin, welcome to reopen this issue.
