### ISSUE TITLE
Parameter 'searchTarget' not found in YAML

### ISSUE THREAD

**Issue by Sohrab1999** [pyrochlore/obsidian-tracker#204]
hi  there I've encountered a problem with creating Trackers and tried so many things and still no solutions 
````tracker
SearchType: Frontmatter
SearchTarget: meditation
Folder: Journal/1 daily
Month: 
````
this is the code that I use to make the tracker but when I click on preview it shows this error: Parameter 'searchTarget' not found in YAML
I have written about meditation in so many notes' yamles and it's not empty 
I would be very grateful if anyone helped me.
<img width="989" alt="Screenshot_20230212_103941" src="https://user-images.githubusercontent.com/31368151/218331758-25ffebc8-0d0f-4d49-b681-3df1bf3d5944.png">

**Comment by Gnarlsi** [comment]
Could it be that you simply have a typo in your frontmatter? There's a "t" missing in meditation.

**Comment by zsmith113** [comment]
> Could it be that you simply have a typo in your frontmatter? There's a "t" missing in meditation.

Agree with this. I would also point out each of the parameters should follow Camel Case convention. First letter of each parameter shouldn't be capitalized
```
searchTarget: frontmatter
searchTarget: meditation
folder: Journal/1 Daily
month:
```
I was able to recreate the error you call out solely by capitalizing the 's' in 'searchTarget' with a working tracker.

**Comment by lazyguru** [comment]
Hi @Sohrab1999 it looks like others have provided answers here. I'm going to close this issue out, however feel free to reopen it or open a new issue if you are still having problems
