### ISSUE TITLE
Counting tag occurences giving wrong results 

### ISSUE THREAD

**Issue by Vi-Sri** [pyrochlore/obsidian-tracker#21]
First of all, great plugin and amazing concept, so kudos to that for the developer. 

Problem statement is, I am trying to fetch the number of todos (by tag) created with respect to the dates and trying to draw a line chart for it. I want to know about two problems i am facing here,

### if Folder has an emoji in its name, Parser doesnt work
First one is, the YAML parser is not parsing a folder name with an emoji, its saying that the folder doesnt exist, dont know if am doing wrong there. 
![Screenshot 2021-05-27 at 7 45 34 PM](https://user-images.githubusercontent.com/17814051/119844893-6fc86a80-bf26-11eb-8824-227aacd60fcf.png)
![Screenshot 2021-05-27 at 7 45 49 PM](https://user-images.githubusercontent.com/17814051/119844906-72c35b00-bf26-11eb-948b-1b7d12e9fbe8.png)

### If i give the root folder as vault, then it returns an absurd result for searching the occurrences of "#todo"
I am confused, since it dint accept the emoji, i gave the root folder as vault and tried to get all the occurences of the tag todo and still it dint work.
![Screenshot 2021-05-27 at 7 46 20 PM](https://user-images.githubusercontent.com/17814051/119846917-2da02880-bf28-11eb-954f-3c9a28cc0351.png)
![Screenshot 2021-05-27 at 7 46 26 PM](https://user-images.githubusercontent.com/17814051/119846924-2f69ec00-bf28-11eb-960b-20352953633a.png)

### Things i am sure about 
- Yes i create todo tags every single day
- The emoji did not work for folder name whatsoever, tried from multiple source (maybe i am missing something here)

**Comment by pyrochlore** [comment]
Thanks for the feedback.

I noticed that the revealed the folder path in error message contains a html img tag.
Did you have another plugin to present image tag as picture in the preview mode, 
so the input for searchTarget actually contains a html img tag?

**Comment by pyrochlore** [comment]
For the second condition using root folder, 
I am not sure why it does not works.
So I made an test project [here](https://drive.google.com/file/d/1aX09zwx-gTXAngC4Yb5P1JjTMRZ3L0yo/view?usp=sharing). 
To test it, just extract it and put the case folder under your vault.

**Comment by Vi-Sri** [comment]
> Thanks for the feedback.
> 
> I noticed that the revealed folder path in the error message contains a html img tag.
> Did you have another plugin to present image tag as picture in the preview mode, 
> so the input for searchTarget actually contains a html img tag?

- I don't quite get the question. But I'll try to answer what I did regarding the folder name. So the objective behind this is.. I have 5 Notes categorised as Work Todos, Personal Todos, Study Todos etc. under the folder "✅ Todos" where I log my todos with a #todo tag and I have another note called Dashboard in the root where I want to display a line chart of number of occurrences of #todo vs date and I am struggling to achieve it through the plugin, so, I copy pasted an emoji with a text for the folder variable in YAML. Its something like this "✅ Todos", while the search target is actually a tag "#todo" , so the variable for YAML as per the documentation is **searchType : tag** and **searchTarget: todo** to count the occurences of "#todo".

- Leaving this emoji matter aside, shouldn't this work either way if I set the folder to the default root of the vault, and shouldn't the tracker plugin search the entire vault and all notes in it for the tag "#todo" and count all the occurences ?

**Comment by pyrochlore** [comment]
Revised
> so the input for searchTarget actually contains a html img tag?

so the input for 'folder' actually contains a html tag?

**Comment by Vi-Sri** [comment]
> Revised
> > so the input for searchTarget actually contains a html img tag?
> 
> so the input for 'folder' actually contains a html tag

That's correct, the folder actually contains the img tag, for the emoji.

**Comment by pyrochlore** [comment]
> Leaving this emoji matter aside, shouldn't this work either way if I set the folder to the default root of the vault, and shouldn't the tracker plugin search the entire vault and all notes in it for the tag "#todo" and count all the occurences ?

It should work, so please give the [test project](https://drive.google.com/file/d/1aX09zwx-gTXAngC4Yb5P1JjTMRZ3L0yo/view) a try. Maybe it's a bug not found yet.

**Comment by pyrochlore** [comment]
> That's correct, the folder actually contains the img tag, for the emoji.

That's it. 
The Emoji in folder name can not be a img tag, its in fact a special character. 
Use the Emoji character as folder parameter will do the work.
You can also check how it works in the test project.

**Comment by Vi-Sri** [comment]
> > Leaving this emoji matter aside, shouldn't this work either way if I set the folder to the default root of the vault, and shouldn't the tracker plugin search the entire vault and all notes in it for the tag "#todo" and count all the occurences ?
> 
> It should work, so please give the [test project](https://drive.google.com/file/d/1aX09zwx-gTXAngC4Yb5P1JjTMRZ3L0yo/view) a try. Maybe it's a bug not found yet.

So i have put your test project into my vault, and, as you said i think we cant have an html img tag in the name of the folder, so i think that is resolved, but i think the issue itself is the behaviour which i observe that, its not exactly counting the todo tags, but rather the number of files with a date as a name of the file with the todo tag ? maybe ? am not sure here. I changed the folder you gave as "✅ Test" to test it in my vault itself, i saw that you created three files, and with the date, its showing the value as 3. So am drawing out the behaviour as this.. correct me if i am wrong. 

So i have these questions in terms of the behaviour of the plugin : 
1. The file name should be a date string ?  
2. The todos are not counted as per line occurences but rather file occurences ? like if there are 5 todos in file A and 3 todos in file B, still the count will be 2 ? 

What support can i give to the development, to implement more cool features to this, because i really want a dashboard based on the statistics of various entities in my vault and i think this is the only plugin that can achieve this.

## Preview mode : 
![Screenshot 2021-05-28 at 12 11 19 PM](https://user-images.githubusercontent.com/17814051/119942107-148e8a80-bfaf-11eb-8695-baedfd91ef6a.png)

## Edit mode :
![Screenshot 2021-05-28 at 12 31 08 PM](https://user-images.githubusercontent.com/17814051/119943447-afd42f80-bfb0-11eb-8674-c90e6969aca3.png)

**Comment by pyrochlore** [comment]
> So i have these questions in terms of the behaviour of the plugin :
>    The file name should be a date string ?

Currently, yes. This plugin use the date string in file name as the x values.
The using of other dataset as x values is a feature on the road map.  

>    The todos are not counted as per line occurences but rather file occurences ? like if there are 5 todos in file A and 3 todos in file B, still the count will be 2 ?

This plugin counts the number of todo tags for each file with date string in file name.
For 5 todos on 2021-05-28 and 3 todos on 2021-05-29, you will get two data points
x: [2021-05-28, 2021-05-29]
y: [                5,                  3]
       
From the result you described, it is very likely a bug. But I cannot repeat it here. I got them rendered properly on my side.
![image](https://user-images.githubusercontent.com/3617615/119983857-4e818000-bff3-11eb-88b2-8299cce9bd6e.png)
Could you kindly send me an example of yours?

> What support can i give to the development, to implement more cool features to this, because i really want a dashboard based on the statistics of various entities in my vault and i think this is the only plugin that can achieve this.

If you got some programming skill, welcome to make a pull request. Or you can [buy me coffees](https://www.buymeacoffee.com/pyrochlore) to support the development.

**Comment by Vi-Sri** [comment]
> > So i have these questions in terms of the behaviour of the plugin :
> > The file name should be a date string ?
> 
> Currently, yes. This plugin use the date string in file name as the x values.
> The using of other dataset as x values is a feature on the road map.
> 
> > The todos are not counted as per line occurences but rather file occurences ? like if there are 5 todos in file A and 3 todos in file B, still the count will be 2 ?
> 
> This plugin counts the number of todo tags for each file with date string in file name.
> For 5 todos on 2021-05-28 and 3 todos on 2021-05-29, you will get two data points
> x: [2021-05-28, 2021-05-29]
> y: [ 5, 3]
> 
> From the result you described, it is very likely a bug. But I cannot repeat it here. I got them rendered properly on my side.
> ![image](https://user-images.githubusercontent.com/3617615/119985418-314db100-bff5-11eb-9308-e866aeafe708.png)
> Could you kindly send me an example of yours?
> 
> > What support can i give to the development, to implement more cool features to this, because i really want a dashboard based on the statistics of various entities in my vault and i think this is the only plugin that can achieve this.
> 
> If you got some programming skill, welcome to make a pull request. Or you can [buy me coffees](https://www.buymeacoffee.com/pyrochlore) to support the development.

Amazing. yeah i think it was a confusion from my side, it works for me too. Thanks a ton for your time on this. ill close this issue for now, i got all my answers from this. Really a useful plugin there. would be happy to support it.
