### ISSUE TITLE
count completed tasks

### ISSUE THREAD

**Issue by gatorkate** [pyrochlore/obsidian-tracker#22]
Could you add the ability to count completed tasks?  For example, I have a task list that includes walking everyday.  Instead of counting the occurrence of the tag #walk, I'd like to count how many times the task 

- [ ] walk

is completed.

**Comment by pyrochlore** [comment]
You can use text searching with regular expression.
Like this
```
searchType: text
searchTarget: '-\s\[x\]\s+walk'
line:
```

**Comment by gatorkate** [comment]
Oh I like that.  Learned something new today!

I'm using this!
