### ISSUE TITLE
add start date and end date to summary

### ISSUE THREAD

**Issue by gatorkate** [pyrochlore/obsidian-tracker#23]
Can you add Start Date and End Date to the summary template variables so that we can see the Start Date and End Date of the latest streak and the Start Date and End Date of the data set.

**Comment by pyrochlore** [comment]
Good to know!
I definitely will add more template variables like these.

**Comment by pyrochlore** [comment]
Hi @gatorkate,

New template variables were added and just released in the new version v1.6.0.
Please take a look at the document about [template variables](https://github.com/pyrochlore/obsidian-tracker/blob/master/docs/TemplateVariables.md).

**Comment by pyrochlore** [comment]
Will close the issue.
More requests and suggestions are welcome.
