### ISSUE TITLE
Accessing and using monthly file title date

### ISSUE THREAD

**Issue by gtquast** [pyrochlore/obsidian-tracker#240]
Hi, I have a monthly journal page with title in the date format "YYYY-MM" like "2023-08.md". 

I want to show tracker data for first to last date of that month. How can I properly access the file name in tracker and append the first and last day (well knowing it could be 28 for Feb or 30 or 31)?

Desired result would be:

startDate: "2023-08-01"
endDate: "2023-08-31"

...but the "-DD" generated so I can use it in the template.

Thank you so much,
Gerrit

**Comment by lazyguru** [comment]
I am not sure this is a bug/issue with the plugin? What you want to do should be doable using JS (I don't have example code, but it should be fairly trivial to grab a date value from the file title and then grab the last day of the month using the date object)
