### ISSUE TITLE
Checkbox in frontmatter does not work

### ISSUE THREAD

**Issue by Maduki-tech** [pyrochlore/obsidian-tracker#243]
Hello, 
I try to create a Habit Tracker, where i use the Checkbox in the Frontmatter. But the Calender View does not work with the Checkbox. I need to use a Number 0 and 1. 

Is there a way to do this?

**Comment by aladmit** [comment]
Hey👋🏼 I was wondering the same thing. I found that plugin [doesn't handle boolean values](https://github.com/pyrochlore/obsidian-tracker/issues/79) in frontmatter at the moment, so there is no way to do that by 'searchType: frontmatter'.

But! Obsidian Checkbox type can guarantee that field value always is going to be either `true` or `false`. It allows us to use text search safely and be sure data always going to look the same way.

My current calendar to track sport habit through checkbox looks like this:
```
searchType: text
searchTarget: 'stretching: true'
month:
```

**Comment by lazyguru** [comment]
There is an open PR that solves this https://github.com/pyrochlore/obsidian-tracker/pull/177. Additionally, my fork has almost every open PR merged on it and I did a release that you can manually install: https://github.com/lazyguru/obsidian-tracker/releases/tag/v1.11.0

**Comment by Maduki-tech** [comment]
> Hey👋🏼 I was wondering the same thing. I found that plugin [doesn't handle boolean values](https://github.com/pyrochlore/obsidian-tracker/issues/79) in frontmatter at the moment, so there is no way to do that by 'searchType: frontmatter'.
> 
> But! Obsidian Checkbox type can guarantee that field value always is going to be either `true` or `false`. It allows us to use text search safely and be sure data always going to look the same way.
> 
> My current calendar to track sport habit through checkbox looks like this:
> 
> ```
> searchType: text
> searchTarget: 'stretching: true'
> month:
> ```

Great this helped me. Works fine for me.

**Comment by certainlyNotHeisenberg** [comment]
Chiming in to say I ran into this issues (of booleans not being parsed correctly) and this fix would be helpful!
