### ISSUE TITLE
Circles in calendar based on boolean properties in frontmatter

### ISSUE THREAD

**Issue by Don-Touch** [pyrochlore/obsidian-tracker#244]
It seems after release of Obsidian 1.4.5 with Properties, Tracker plugin should start supporting boolean-type properties.
At least in calendar it doesn't work anymore. I've been using 0/1 values to track habits. Now I'm converting them to false/true.
Calendar doesn't reflect true values as Rings

**Comment by lazyguru** [comment]
There is an open PR that solves this #177. Additionally, my fork has almost every open PR merged on it and I did a release that you can manually install: https://github.com/lazyguru/obsidian-tracker/releases/tag/v1.11.0

**Comment by Don-Touch** [comment]
thanks, dude
