### ISSUE TITLE
Boolean "true' doesn't work the way "1" did before Properties happened

### ISSUE THREAD

**Issue by sh4d0wl3ss** [pyrochlore/obsidian-tracker#247]
HI Folks,   I have a calendar habit tracker that worked swimmingly before the change to properties.  It seems that the property checkbox results in a "true" in markdown where before it was a "1".  Sure enough if I manually change a note with a checked property in the front matter that had been "true" to "1" that note's checkbox property appears in my monthly calendar.    How can I rewrite the code below to work with "true" instead of "1" for properties that are checkboxes?

searchType: frontmatter
searchTarget: hands=true, eyes=true, walk=true, workout=true
datasetName: Hands, Eyes, Walk, Workout
folder: 2023
month:
	mode: annotation
	startWeekOn: 'Mon'
	color: green
	headerMonthColor: orange
	dimNotInMonth: false
	annotation: 👐,👀,🚶‍♂,💪
	showAnnotationOfAllTargets: true

Thanks

**Comment by lazyguru** [comment]
There is an open PR that solves this #177. Additionally, my fork has almost every open PR merged on it and I did a release that you can manually install: https://github.com/lazyguru/obsidian-tracker/releases/tag/v1.11.0

**Comment by sh4d0wl3ss** [comment]
Still no luck.  I copied the files in the #177
styles.css
main.js
manifest.json
to the plugin folder and that just turned off the plugin, so I had to reinstall it.   No change in regard to treating "true" in the frontmatter to the way "1" was treated before.   Here's my code that worked before Properties were added.  Is there something better I should use?  
```tracker
searchType: frontmatter
searchTarget: hands, eyes, walk, workout
datasetName: Hands, Eyes, Walk, Workout
folder: 2023
month:
	mode: annotation
	startWeekOn: 'Mon'
	color: green
	headerMonthColor: orange
	dimNotInMonth: false
	annotation: 👐,👀,🚶‍♂,💪
	showAnnotationOfAllTargets: true
```

Each of the targets is either "true" or blank, per the way checkboxes function now. 
Thanks.

**Comment by dml0sc** [comment]
I tried to install v1.11.0 and I continue having the same problem with parsing booleans from the frontmatter.

**Comment by sh4d0wl3ss** [comment]
Hi Yes.  Turned it on and it works as before. The code I pasted above will work if the target is 1 but not if it is true.

**Comment by lazyguru** [comment]
Here is a test vault using your settings and the v1.11.0 release from my fork (and the dataview plugin)
[Tracker Test.zip](https://github.com/pyrochlore/obsidian-tracker/files/12851158/Tracker.Test.zip)
![Screen Shot 2023-10-09 at 5 18 34 PM](https://github.com/pyrochlore/obsidian-tracker/assets/612340/9cd5c0c1-6151-48b9-8804-cc7f150d08b6)

**Comment by lazyguru** [comment]
![Screen Shot 2023-10-09 at 5 19 53 PM](https://github.com/pyrochlore/obsidian-tracker/assets/612340/0b08ad54-c9fe-4956-985f-a2b7070b8d12)
![Screen Shot 2023-10-09 at 5 19 48 PM](https://github.com/pyrochlore/obsidian-tracker/assets/612340/22a12c9c-4622-4e56-b98c-6dbc1ba14c8b)

**Comment by lazyguru** [comment]
![Screen Shot 2023-10-09 at 5 20 34 PM](https://github.com/pyrochlore/obsidian-tracker/assets/612340/b8c6e4ad-e2ce-4b23-a123-cc738ffa2c4f)

**Comment by sh4d0wl3ss** [comment]
Thanks.  I see that though I'd put in your new files for 1.11 without having disabled and then reenabled.  Though it now works the version reported in the Community plugin browser is still 1.10.9.    That just confused me that it didn't take the first time.

**Comment by sh4d0wl3ss** [comment]
That solves it for me.
