### ISSUE TITLE
Support hex/rgb colors

### ISSUE THREAD

**Issue by jeloi** [pyrochlore/obsidian-tracker#25]
Currently color customization is supported using plain words
```
bar:
	barColor: green
```

It'd be great to be able to customize colors using hex/rgb:
```
bar:
	barColor: #ffaa11
```

**Comment by pyrochlore** [comment]
Hi,
Because # denotes comments in YAML, 
you have  to wrap the text in single quotes.

‘#ffaa11’ should do the work.

**Comment by pyrochlore** [comment]
Hi @evilthebeth ,

You can wrap the whole input as a string, e.g. '#5811ee, darkseagreen'.
Or use YAML list ['#5811ee', 'darkseagreen'].

**Comment by evilthebeth** [comment]
> Hi @evilthebeth ,
> 
> You can wrap the whole input as a string, e.g. '#5811ee, darkseagreen'.
> Or use YAML list ['#5811ee', 'darkseagreen'].

ok, will try, thanks a lot :)

**Comment by pyrochlore** [comment]
I will close the issue here.
Welcome to reopen it if anything bothers you.
