### ISSUE TITLE
[Question] Count the occurrences of particular frontmatter? 

### ISSUE THREAD

**Issue by jhilker98** [pyrochlore/obsidian-tracker#257]
Hey there, thanks for creating this. I've tried to use this for creating dashboards for a novel (in particular, the characters), and I'd like to be able to count the number of appearances of a particular piece of frontmatter. This is my current approach, but I'm getting the "invalid Y value in notes" error. What would be the easiest way to handle this?

```
searchType: fileMeta, frontmatter
searchTarget: cDate, Gender
folder: 04 Fiction/041 The Ashes Chronicles/01 Ashes/01 Characters
xDataset: 0
accum: true
pie:
```

**Comment by lazyguru** [comment]
Can you provide a little more detail?  What result are you looking for? (Can you provide a mock example of what you are expecting?). Just looking at what you have I would expect something like:

Male: 5
Female: 12

But I don't understand where cDate comes in? (I ass-u-me you have files in "01 Characters" like "Ned.md", "Jon.md", "Arya.md")

**Comment by jhilker98** [comment]
I did have files in "01 Characters" like what you had said - I was getting the "no valid date as X values" error, which is what I had used the cDate to temporarily fix - what you had in the comment was what I was thinking.

**Comment by lazyguru** [comment]
If you are just wanting a count like what I had you don't need this plugin. You should be able to achieve what you are after using a regular dataview query. Here is something that sounds close to what you are after: https://forum.obsidian.md/t/can-dataview-count-occurrences-of-a-value-author-name-and-sort-by-that-number/53911

**Comment by jhilker98** [comment]
Oh, alright! I was wanting to break it down into a pie chart, which is why i was confused

**Comment by lazyguru** [comment]
Tracker is for tracking things against time. It's not really a standalone visualization tool. If you just want to display static data in a pie chart you might want to look at the Obsidian Charts plugin

**Comment by lazyguru** [comment]
Alternatively, here's something that might work (I didn't read the whole page, but it skimming it sounded like what you are doing): https://forum.obsidian.md/t/dataviewjs-and-charts-how-to-make-a-pie-chart-with-values-calculated-in-dataviewjs/71405

**Comment by jhilker98** [comment]
Thanks much!
