### ISSUE TITLE
Feature Request: Track completed / uncompleted tasks

### ISSUE THREAD

**Issue by ConnorMeyers** [pyrochlore/obsidian-tracker#28]
It would be super useful to track the number of finished or unfinished tasks in specific files. 

Referring to markdown tasks
- [x] task
- [x] finished task 

Use case:
To have a graph spanning days visualizing how much I got done or didn't get done.

**Comment by pyrochlore** [comment]
Hi, 
Thanks for the suggestions.
I plan to have a new input type (searchType) ‘task’ to collect these kinds of data.
The searchTarget could be task name ( include * for all tasks).
And a filter parameter for filtering out checked or unchecked items. 
What do you think about this?

**Comment by ConnorMeyers** [comment]
Sounds great, I look forward to trying it out when it's done.

love the plugin!

**Comment by pyrochlore** [comment]
@ConnorMeyers The feature was just released with version 1.8.0
[Here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTask.md) are some examples.
Enjoy tracking.

**Comment by pyrochlore** [comment]
Will close the issue.
Welcome to report more bugs or make suggestions.
