### ISSUE TITLE
Feature Request: Pie Chart graph type

### ISSUE THREAD

**Issue by thatdwayne** [pyrochlore/obsidian-tracker#29]
For some items, such as "percentage of days in the office" it would be helpful to have a pie chart graph type. I already track this using a bar chart (with a -1 penalty so I can see "up bars" when I'm in the office and "down bars" when I'm not, but would love to track various percentages (last 30 days, last 90 days, and last 365 days).

Thanks for considering this!

**Comment by pyrochlore** [comment]
Hi @thatdwayne ,

I am glad you noticed the parameter `penalty` which I didn't mention a lot. 
I actually use it everyday for my own tracker.

Back to the feature request.
To plot a pie chart for "percentage of days in the office", 
except collecting data "days in the office" (by template variable {{numDaysHavingData}}), 
we also need data of "days 'not' in the office" which is not possible for now.

Though I can add a template variable like {{numDaysNotHavingData}},
I prefer to implement data arithmetics first, so we can get days off by {{days}} - {{numDaysHavingData}}.

**Comment by pyrochlore** [comment]
The feature pie chart and expressions were implemented and released in version 1.9.0 just now.
Bug reports and any feedback are welcome.

**Comment by pyrochlore** [comment]
Will close the issue.
Questions and suggestions are still welcome.
