### ISSUE TITLE
Make the regex a bit more relaxed

### ISSUE THREAD

**Issue by Cito** [pyrochlore/obsidian-tracker#3]
The regex for searching tagged values is very strict. For instance, it ignores the following:
```
My weight todaay was #weight:100kg!
```
I think the parser should allow and ignore any punctuation characters after the value.

**Comment by pyrochlore** [comment]
Good point, will add this in next release.

**Comment by pyrochlore** [comment]
The regex was modified to allow ".!,?;~-" characters after the unit or the value. It will be merged to the master branch in the next release.

**Comment by pyrochlore** [comment]
Code merged to master and released in version 1.1.0.
