### ISSUE TITLE
Summary cannot display in a line graph？

### ISSUE THREAD

**Issue by EgnaroJQ** [pyrochlore/obsidian-tracker#318]
I tried to add summary to a line graph but it failed to display.
My code is as below:
```tracker
searchType: frontmatter 
searchTarget: Workout (min) 
folder: 00 Diary 
startDate: 2024-02-12 
line: 
	title: Workout(min)
summary:			
	template: "Total: {{sum()}} hours"
```
Did I write something wrong? Or summary cannot show in a line graph?

**Comment by lazyguru** [comment]
@stracker-phil is correct. You need to do 2 separate dataview blocks
