### ISSUE TITLE
Feature Request: yAxisInterval

### ISSUE THREAD

**Issue by jpmoo** [pyrochlore/obsidian-tracker#32]
Would love to specify the interval for the y-axis. Right now it goes by .5 in my bar/line graph trackers. However, it would be handy to be able to say the interval should be 1, or 2, etc. instead of .5.

**Comment by pyrochlore** [comment]
Will add :)

**Comment by jpmoo** [comment]
Thank you!!

**Comment by pyrochlore** [comment]
This feature was implemented and released with version 1.10.0.
[Here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestAxisIntervalAndFormat.md) is the example.
Bug or issue reports are welcome.

**Comment by pyrochlore** [comment]
Will close this issue.
Please fire issues if there are more questions or suggestions.
