### ISSUE TITLE
Frontmatter / property using boolean or checkbox

### ISSUE THREAD

**Issue by Braveheart53** [pyrochlore/obsidian-tracker#331]
## Expected Behavior

If using a color chart or calendar, say month, and assigning the searchTarget as a property in the frontmatter, if the property is a checkbox which is a boolean, then it would only be shown on the calendar if the value of the checkbox is true or 1.

## Current Behavior

If selected, it does show the boolean value but in terms of highlighting, it shows regardless of the value.

## Possible Solution

I am hoping I missing a command under the month where I can set it based on value. If not, this would be the solution based on property type and value thereof.

## Steps to Reproduce (for bugs)

1. In the note or daily note file
```
---
clock-in: 07:55
clock-out: 17:00
Attendance: false
---
```
2. In a tracker HUD or file use the following:
```tracker
searchType: frontmatter
searchTarget: "Attendance"
endDate: 2024-03-31
folder: "Daily"
datasetName: "Attendance This Month"
month:
    startWeekOn: 'Sun'
    threshold: 40
    color: tomato
    headerMonthColor: orange
    dimNotInMonth: false
    todayRingColor: orange
    selectedRingColor: steelblue
    showSelectedValue: true
```
4. If selected, it does show the boolean value but in terms of highlighting, it shows regardless of the value.

## Context

I am trying to track attendance at a glance on a calendar using a template with a checkbox as the property for a single person. So in my daily journal it is a single click after a template is applied.

**Comment by lazyguru** [comment]
You need to remove: `threshold: 40` from your data query

**Comment by Braveheart53** [comment]
> You need to remove: `threshold: 40` from your data query

Perfect. This was not an issue or bug, just ignorance of this user. Thank you for the feedback and please close.
