### ISSUE TITLE
How to get the value in [key:: value] or (key:: value) ？

### ISSUE THREAD

**Issue by fantuyuan** [pyrochlore/obsidian-tracker#338]
Now only get the value of key:: value，But I need to use the [key::value] or (key:: value) format.

**Comment by lazyguru** [comment]
Please use the issue template. It will help with providing you answers.

**Comment by fantuyuan** [comment]
> Please use the issue template. It will help with providing you answers.请使用问题模板。这将有助于为您提供答案。

It's not a problem with [] or (), please delete this issue.
