### ISSUE TITLE
Changing the size of the chart

### ISSUE THREAD

**Issue by dummifiedme** [pyrochlore/obsidian-tracker#34]
I tried looking for a way to change the plotted graph area, but couldn't find any way.
Can the area or the size of the graph be changed? 

Currently it previews as a square block, I intend to have it full page width and maybe scrollable too. Possible?

**Comment by pyrochlore** [comment]
Parameter `fixedScale` and `fitPanelWidth` are prepared for you!
Please also check the example [here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestScalingAndPositioing.md)

**Comment by dummifiedme** [comment]
These functions are just scaling the image..not per se extending the width only. I mean, the y-axis should be extendable, right?

**Comment by pyrochlore** [comment]
Hi, do you mean change the aspect ratio of chart area?
Keep the height and increase the width only?

**Comment by dummifiedme** [comment]
I wish to increase the y-axis. Not like stretching the whole "image"

**Comment by pyrochlore** [comment]
If you just want to extend the range of y values on y-axis, use parameter `yMin` and `yMax`. 

But if you want to change the 'length' of y-axis only,
the current code does not allow it.

That should be taken carefully or the entire layout would be messed up.

**Comment by dummifiedme** [comment]
Okay, thanks! :)

**Comment by dabathehutt** [comment]
+1 for this! 

Especially full-width graphs would be great to have

**Comment by neonplants** [comment]
Hey! Just want to +1 full-width graphs. This is becoming crucial for me as my tracker graphs age, and more and more data gets packed into a tiny horizontal space. It's becoming harder over time to derive meaning from the graph. You can see what I mean here.
<img width="431" alt="Screen Shot 2022-02-25 at 8 57 32 PM" src="https://user-images.githubusercontent.com/26178851/155824541-9450c409-fde0-4d4b-989c-4098e9ed56ea.png">
I noticed this feature isn't on the roadmap. Does it seem like something you'll be able to implement at some point? 
I wish we could pay to support your efforts!

**Comment by neonplants** [comment]
Thanks @229c9cf0 ! It's rough because I do use the other graph types extensively. @pyrochlore what do you think?

**Comment by nousernameavailableanymore** [comment]
Is there any update on this?

This is such a feature rich plugin.
Which is why I was all the more surprised that there was no way to change the aspect ratio from the current 1:1 to something more suitable for line graphs like 4:1 or similar.
Especially since the fix seems so easy as outlined above.

Adding this feature would be highly appreciated 🙂

**Comment by andrew-wiskus** [comment]
+1 `aspectRatio` or being able to hard-set the width/height would be awesome.. 

Could anyone recommend a different chart to use for line-data that has this customization? I want to make some wide ones for my ultrawide dashboard

**Comment by steebus** [comment]
+1 for sure!

**Comment by AndyJZhao** [comment]
+1 for sure!

**Comment by RadioNoiise** [comment]
Hi, to complete @229c9cf0 's suggestion : it seems to work perfectly using "600, 300" instead. The axes and ticks keep their original sizes.

**Comment by CoderRuq** [comment]
+1

**Comment by pictoys** [comment]
+1 from me

**Comment by zhangyiy0223** [comment]
+1 from me

**Comment by alayhi** [comment]
+1 from me - 1:1 makes allot of charts unreadable

**Comment by xiaopin129** [comment]
+1 from me

**Comment by lazyguru** [comment]
1.12.0 (just released) adds an `aspectRatio` parameter that _should_ solve for this issue. See #239
