### ISSUE TITLE
How to capture decimal values?

### ISSUE THREAD

**Issue by dummifiedme** [pyrochlore/obsidian-tracker#35]
I am using this query. How can I have it capture '2.5' hours?

```
searchType: text  
searchTarget: 'Studied for\s+(?<value>[0-9]+)\s+hours'
```

I found this regex but don't really know how to name it' <value>' -- `?[0-9]*\.?[0-9]*`
😓

**Comment by pyrochlore** [comment]
Try 'Studied for\s+(?\<value\>[\\-]?[0-9]+[\\.][0-9]+|[\\-]?[0-9]+)\s+hours' to capture 'Studied for 2.5 hours'.
This one will accept integer or floating number.

**Comment by dummifiedme** [comment]
Thanks!
