### ISSUE TITLE
Month tracker not working as expected with values

### ISSUE THREAD

**Issue by suniluci** [pyrochlore/obsidian-tracker#37]
```tracker
searchType: table
searchTarget:  _Dailies/Tracker/tracking[0][0], _Dailies/Tracker/tracking[0][11]
xDataset: 0
month:
    startWeekOn:
    threshold: 2
    color: green
    headerMonthColor: orange
    dimNotInMonth: false
    todayRingColor: orange
    selectedRingColor: steelblue
    circleColorByValue: true
    showSelectedValue: true
```  

I use a table for tracking everything. I had a count of habits accomplished in a day at the end of the table. I had values greater than 2 in zero-indexed column 11, but the links and solid circles are not showing up. Am I missing something? 

![image](https://user-images.githubusercontent.com/4607718/124393946-ec7eff00-dcb1-11eb-8621-14822c0ce844.png)

**Comment by pyrochlore** [comment]
Will do some test on it!

**Comment by suniluci** [comment]
Thank you!

**Comment by pyrochlore** [comment]
The fix for this issue was just released in version 1.8.1.
I also prepared an example for your case [here](https://drive.google.com/file/d/1brISX4i4VtMgxGhW8JBdACTXiy5w9XgE/view?usp=sharing).
Just unzip the file and put the folder 'case' under your vault.

If the problems remain, don't hesitate to tell me know.

**Comment by suniluci** [comment]
This is awesome, thanks a lot! It works as expected :)

**Comment by SalahAdDin** [comment]
It is happening to me with the latest version:
![image](https://user-images.githubusercontent.com/5034215/222931536-874acd88-f213-465c-b34d-f4a298a3a98d.png)
With annotations I can see my activities, without it, I don't see any value.
