### ISSUE TITLE
Counting symbols as value

### ISSUE THREAD

**Issue by fncll** [pyrochlore/obsidian-tracker#38]
Right now I have a lot of historical data for mood tracking that is of the form:

```
07:37 [[🧠]] [[🔷🔷]] note of indeterminate length
more stuff 
blah blah
etc
19:36 [[🧠]] [[🔷🔷🔷] another note
```

My question: is there a way to configure tracker to see the lines with the timestamp above as input for mood and use the count of the symbols as the value for each? Effectively seeing the first line as equivalent to:

```
Mood: 2
```

etc?

**Comment by pyrochlore** [comment]
Hi @fncll,

Two questions here.
First, are those data in one file or spread in notes?
Second, is it acceptable to sum the data in the same day?
Currently, the time grain of this plugin is a day. (may change in future)

**Comment by fncll** [comment]
Ah, got it. The lines are spread randomly throughout the daily notes and summing the count per day wouldn't work in my scenario. Thanks for the prompt help!
