### ISSUE TITLE
Emoji Tracking

### ISSUE THREAD

**Issue by isaacmdt** [pyrochlore/obsidian-tracker#39]
I'm using the Emoji Tool Bar [GITHUB](https://github.com/oliveryh/obsidian-emoji-toolbar) from Oliveryh.

I know that it's just images. Is there any support for this. The text type and the star examples didn't work.

**Comment by pyrochlore** [comment]
Hi,
I have installed the plugin and done few tests.
The emojis added from the plugin you mentioned are special characters,
so the plugin should be able to track them by `searchType` `text`.

I also prepared an example [here](https://drive.google.com/file/d/1g5NlQkTMPRNMdEb4kPVIPuK2Xyx9LIyq/view?usp=sharing).
Please download then unzip and put the folder 'case' under your vault to see if it works or not.

**Comment by isaacmdt** [comment]
Thank you,
You are correct. I did some troubleshooting. Had some updates on other plugins. After a quick app restart, it all started working. Thank you. Love the plugin.

**Comment by pyrochlore** [comment]
Will close the issue.
More questions or suggestions are welcome.
