### ISSUE TITLE
Failed to load plugin when upgrading to Obsidian version 1.7

### ISSUE THREAD

**Issue by lulunac27a** [pyrochlore/obsidian-tracker#390]
## Expected Behavior

Should successfully load the plugin.
## Current Behavior

The tracker plugin failed to load when Obsidian was updated to version 1.7, but older versions of Obsidian works as expected.

## Possible Solution

None.
## Steps to Reproduce (for bugs)

1. Open Obsidian
2. Display error message on top-right of Obsidian window

## Context

Can't use the plugin at all to track my data.

**Comment by lazyguru** [comment]
What version of Obsidian Tracker do you have? I have 1.14.0 running on Obsidian 1.7.4 on MacOS without errors. Can you please provide some screenshots and example files?

**Comment by lulunac27a** [comment]
I accidentally chose the wrong plugin, it was tracker-plus, not tracker.

<img width="312" alt="Screenshot 2024-10-17 at 11 15 43 PM" src="https://github.com/user-attachments/assets/47a369a2-7b27-453e-8d99-f5b0d1915ad5">

**Comment by lulunac27a** [comment]
When I load this plugin with [Tracker+](https://github.com/greater-than/Obsidian-Tracker-Plus) enabled it failed to load, but it works by unloading the [Tracker+](https://github.com/greater-than/Obsidian-Tracker-Plus) plugin.
<img width="304" alt="Screenshot 2024-10-25 at 2 59 04 PM" src="https://github.com/user-attachments/assets/736f5d5c-658f-4ff1-a185-ef87f5305c2d">

**Comment by lazyguru** [comment]
My understanding of Tracker+ was that it was a community member that saw this plugin not getting updates and decided to essentially fork this one and rewrite large chunks of it. That happened about the same time that I managed to get in touch with pyrochlore and be added as a maintainer here. That's a long way of saying "I don't think the 2 plugins are compatible as they both solve the same problem"
