### ISSUE TITLE
regex in date format

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [pyrochlore/obsidian-tracker#41]
I have a lot of old journal entries which have slightly different file name structure.
An example of Old format is `YYMMDD - grace` which in obsidian is as `YYMMDD[ - grace]`

For current year, i am using new format as `YYMMDD[ - journal]`

Is it possible to pull data from the both using regular expression for `dateformat` like `YYMMD[- /journal|grace/]` ?

Thanks for your work.

**Comment by pyrochlore** [comment]
Hi @1nsp1r3rnzt,

Though we have made changes for different kinds of date formats,
we cannot parse date formats using regex yet.

That would be an ultimate solution to the `dateFormat` for everyone.
Will add it in the coming release (maybe in the version after the next one).

**Comment by pyrochlore** [comment]
This feature was implemented and released with version 1.10.0.
[Here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestDateFormats.md#relative-date-input-for-startdate-and-enddate) is the example.
Bug or issue reports are welcome.

**Comment by pyrochlore** [comment]
Will close this issue.
Please fire issues if there are more questions or suggestions.
