### ISSUE TITLE
Count Task with sub tags

### ISSUE THREAD

**Issue by rapatel0** [pyrochlore/obsidian-tracker#44]
I use Tags to label some of my tasks

```
-  [ ] #Health/Water  - Fill water Jug 
-  [ ] #Routine/maintenence - Clean out inbox
-  [ ] #Health/Vitamins Take vitamin B12
-
```

Is there any way to filter tasks by both tag and task? Tried to do it but running into issues

**Comment by pyrochlore** [comment]
Yes you can.

The searchTarget for task actually is very flexible and can accept text or regex.

Will post an example here later.

**Comment by pyrochlore** [comment]
![image](https://user-images.githubusercontent.com/3617615/126258746-80fe8226-c713-4e4d-b2c5-0fa5e166c4a2.png)

Notice: the whole value of `searchTarget` should be wrapped in single quotes

**Comment by pyrochlore** [comment]
This issue will be closed.
Further questions or suggestions are still welcome.

**Comment by tommertron** [comment]
Hi there,

I am trying to do a search in this exact way, but it still only seems to find instances where the *whole* text of the task matches the searchType. 

Here is what I have:

```tracker
searchType: task.notdone
searchTarget: '#waitingon'
folder: 'Daily Notes'
summary:
    template: "Total count: {{sum()}}"
```

This will find tasks that are exactly named "#waitingon" but not if that tag is included in the text of the task somewhere.

**Comment by tommertron** [comment]
So I was able to get the search working using the following regex:
searchTarget: '.*\#waitingon*'

It's kind of weird though, because the example above is definitely not written like that.
