### ISSUE TITLE
Time values cannot be tracked when included as Dataview fields

### ISSUE THREAD

**Issue by wenlzhang** [pyrochlore/obsidian-tracker#46]
Following the time values example, the following can be tracked if they are included in the front matter. However, if they are defined as Dataview inline fields, they cannot be tracked with this plugin.
```
clock-in:: 8:1
clock-out:: 17:0
sleep:: 9:2 pm/6:37 am
```

The following gives no results:

``` tracker
searchType: dvField
searchTarget: sleep[0], sleep[1]
valueShift: -24:00, 00:00
datasetName: Sleep, WakeUp
line:
    title: "Sleep"
    yAxisLabel: "Time (24h)"
    lineColor: yellow, red
    showPoint: true
	showLegend: true
```

Am I missing anything in the query above?

**Comment by pyrochlore** [comment]
Will do some tests on this.

**Comment by pyrochlore** [comment]
Thanks for the feed back.
A bug in the search pattern for `dvField` was found and fixed.
Will be released soon in the next version.

**Comment by pyrochlore** [comment]
The fix was just released with version 1.9.1.

**Comment by wenlzhang** [comment]
Thanks for the update!

It is a little weird that it gives the error message: Not all values in time format, when using the following as Dataview fields.
```
clock-in:: 8:1
clock-out:: 17:0
```

**Comment by pyrochlore** [comment]
Will check it.

**Comment by pyrochlore** [comment]
Sigh, another regex problem, sorry for the buggy update.
Will fix it.

**Comment by wenlzhang** [comment]
Great! It's working now.
