### ISSUE TITLE
Support more operations/units for time values

### ISSUE THREAD

**Issue by wenlzhang** [pyrochlore/obsidian-tracker#47]
In the time value example, one can use `8:1` in the front matter to denote one minute past eight in the morning. It would be great to support more operations like this, e.g. something like the following:

- `00:01:30` or something like 1min30sec for 1 minute and 30 seconds
- `01:01:30` or something like 1h1min30sec for 1 hour, 1 minute and 30 seconds

I am not sure what is the best way to do this, but it would be great to be able to denote time values in a more flexible way.

**Comment by pyrochlore** [comment]
Here are all the time format supported now,

const timeFormat = [
    "HH:mm",
    "HH:m",
    "H:mm",
    "H:m",
    "hh:mm A",
    "hh:mm a",
    "hh:m A",
    "hh:m a",
    "h:mm A",
    "h:mm a",
    "h:m A",
    "h:m a",
];

No unit down to seconds included.
If the unit is required, I can add it.

**Comment by wenlzhang** [comment]
Thanks for the detailed explanation! It would be great to include second in the unit, which can be very useful for recording exercises.

**Comment by pyrochlore** [comment]
The feature was just released in version 1.9.2.
Please give it a try.

**Comment by wenlzhang** [comment]
Woks like a charm!

Also, something like `01:01:70` would give the error message saying that it is not the correct time format, which is as expected.
