### ISSUE TITLE
Use `daily-notes-interface` for user settings

### ISSUE THREAD

**Issue by liamcain** [pyrochlore/obsidian-tracker#5]
Instead of asking users to input their daily note format + their daily notes folder, I recommend you use the`daily-notes-interface` npm package so that you can keep these values in sync with the Daliy Notes plugin.

https://github.com/liamcain/obsidian-daily-notes-interface

**Comment by pyrochlore** [comment]
Great module. Will look into it. Thanks.

**Comment by pyrochlore** [comment]
Done in the dev branch. Will merge to master in the next release.
