### ISSUE TITLE
Getting No notes found under this given search condition

### ISSUE THREAD

**Issue by jmaver** [pyrochlore/obsidian-tracker#50]
I have tried what seems like a million variations of tests, and nothing gets past this error.

Here is a sample note with these fields at the beginning of the note for links, tags, and dataview:

Author:: [[Charles Duhigg]]
ReadDate:: 2021-08
SourceType:: Book
Tags:: #books/selfhelp 

---

Note text is here

And here are a bunch of tracker queries:
``` tracker
searchType: fileMeta
searchTarget: mDate
folder: /
line:
    title: "Line Chart"
```
No notes found under the given search condition

``` tracker
searchType: fileMeta
searchTarget: size
folder: 
endDate: 2021-01-31
line:
    title: File Size Variation
	yAxisLabel: Size
	yAxisUnit: bytes
```
No notes found under the given search condition

``` tracker
searchType: tag
searchTarget: books/selfhelp 
folder: 
startDate:
endDate:
summary:
    style: "color:white;"
```
No notes found under the given search condition

```tracker
searchType: text
searchTarget: 'ReadDate:\s(?<value>[0-9]+)'
summary:
```
No notes found under the given search condition

So, I am obviously missing some key simple setup thing, but I don't know what. :(

**Comment by pyrochlore** [comment]
Thank you for your patience on trying these.

What is the date format on your daily notes' title?
The format of the title (`dateFormat`) is the most common issues users met.
Without a proper setting, a user will get "no notes found" messages.
I will try to improve the error messages in the next version.

---

Also there are some concepts need to be clarify.
Tracker track 'numbers' or 'occurrences'.

For the first case,
```
searchType: fileMeta
searchTarget: mDate
```
It returns dates, not numbers, so no valid values found.

```
searchType: fileMeta
searchTarget: size
```
The search returns numbers, OK to proceed. 

```
searchType: tag
searchTarget: books/selfhelp 
```
The search returns the number of occurrences of tag 'books/selfhelp' in a note

**Comment by jmaver** [comment]
I don't have daily notes on at all. The note I am trying it in is 📚Reading List. I also tried it in an untitled note with nothing else.

Thanks for the tips above. I was mostly just trying to get anything to work. What is the simplest possible test that is guarnateed to show something except this warning and I will do that. :)

**Comment by pyrochlore** [comment]
Will close this issue since there are no more questions.
More suggestions and questions are welcome.
