### ISSUE TITLE
Exemples with databases files

### ISSUE THREAD

**Issue by robertofgama** [pyrochlore/obsidian-tracker#51]
hello, thank you for plugin, i like to request if is possible in examples section, you put the md files with the data that the examples is using, because i am having a little problens to parsing my data, and with complete examples will be more easy to me learn the plugin funcions.

**Comment by robertofgama** [comment]
hello, thank you for plugin, i like to request if is possible in examples section, you put the md files with the data that the examples is using, because i am having a little problens to parsing my data, and with complete examples will be more easy to me learn the plugin funcions.

**Comment by pyrochlore** [comment]
Hi @robertofgama,
Example files include code blocks and sample data are all placed under folder 'examples'.
To see the sample data, please check these two folder 'examples/diary' and 'examples/data'.

**Comment by robertofgama** [comment]
Sorry, I really hadn't seen that files, is all what i needed, thank you a lot
