### ISSUE TITLE
scaling values by a fixed factor

### ISSUE THREAD

**Issue by samarkamat** [pyrochlore/obsidian-tracker#58]
Hello and thank you for this fantastic plugin! 
I'm doing a self experiment where i track my time in 15m increments, and i'd like to graph things like "time spent sleeping" in hours, not # of 15m increments. 

Hence, **i'd like to apply a fixed factor of 0.25** to my `searchType: text` occurrence count. Is this possible to do now?
Thanks again!

**Comment by samarkamat** [comment]
I suspect this could be solved using Regular Expressions, but I'm failing to achieve this
https://github.com/pyrochlore/obsidian-tracker/blob/f5af378ec870bbfde0eca3e3a644491b4ddc7f30/examples/TestRegex.md#count-values

**Comment by pyrochlore** [comment]
What is the output type you need?
For now, expression can be used in summary, pie, and bullet.
And you can do arithmetics in it.

**Comment by samarkamat** [comment]
`constValue` solved it! Thanks so much!
