### ISSUE TITLE
Can it track by adding a variable after text

### ISSUE THREAD

**Issue by 5eagull** [pyrochlore/obsidian-tracker#6]
Can it track by adding a variable after text, such as  "weightlifting: 10".
sometimes use the label to track, Obsidian label system will look very confusing .

**Comment by pyrochlore** [comment]
> Can it track by adding a variable after text, such as "weightlifting: 10".
This plugin can track value-attached tags like "#weight:60.0kg".
Note that there is no space between the colon and the value.
Extra spaces in between will make the tag and the value syntactically fall apart.
> sometimes use the label to track, Obsidian label system will look very confusing .
I am not sure what you met here, could you give me some examples or pictures showing the problems?

**Comment by pyrochlore** [comment]
By the way, if you really need a space between the colon and the value.
There is a feature on the road map, allowing users to define regular expressions in searchTarget.
It will be there in the near future.

**Comment by lll637637** [comment]
> I am not sure what you met here, could you give me some examples or pictures showing the problems?
> I would be more than happy if the problem can be solved.

This is actually very simple, just don't want to make statistics items appear in the obsidian label. 

>By the way, if you really need a space between the colon and the value.
>There is a feature on the road map, allowing users to define regular expressions in searchTarget.
>It will be there in the near future.

Sorry for the misunderstanding, the presence or absence of spaces is not important.

**Comment by pyrochlore** [comment]
I got it. 
That's why I'm going to implement text search with regular expression.
With that feature, the value in text can be 'extracted' using regex.
As I mentioned, it's on the road map and will be there in near future.

**Comment by pyrochlore** [comment]
Seems this issue is more important than I thought.
Not too many people like to use tags in their articles.
Thanks for letting me know this.

**Comment by pyrochlore** [comment]
Done in the dev branch. Will merge it to master in the next release.

To track something like "weightlifting: 10", now you can use a regular expression while using 'text' as searchType. See [here](https://github.com/pyrochlore/obsidian-tracker/blob/dev/examples/TrackWithRegex.md) for the detail usage.

Another option is to put the information in the frontmatter, like
\---
tags:
weightlifting: 10
\---
Then use the new searchType 'frontmatter' to do the search. Check [MoodTracker](https://github.com/pyrochlore/obsidian-tracker/blob/dev/examples/MoodTracker.md) for an example.
