### ISSUE TITLE
Dev documentation

### ISSUE THREAD

**Issue by cgourlay** [pyrochlore/obsidian-tracker#62]
Love this plugin!

I think I may have come across an issue. Before raising an issue I wouldn't mind having a go to try and fix myself and create a PR.

Can you provide instruction on how you (or what needs to be done) setup the dev environment locally?

**Comment by pyrochlore** [comment]
Hi @cgourlay ,

Glad you like it.

Here are the steps to setup the dev environment locally.

1. Have Node.js installed
2. Clone this repository to folder {Tracker Plugin}
3. Under folder {Tracker Plugin}, run 'npm install' to install modules 
4. Under folder {Tracker Plugin} ,run 'npm run dev' to build the project and copy the results to {Tracker Plugin}/examples/.obsidian/obsidian-tracker for you.
This also detects the changes in the repository and rebuild it if necessary.
5. Open the folder {Tracker Plugin}/examples as a vault from Obsidian, enable the Tracker plugin from settings
6. Open any of the {Vault}/TestXXX.md files to check if graphs are rendered 

If graphs in test examples are rendered, you are ready to edit the existing code.
