### ISSUE TITLE
File size query gives different results when using cDate and mDate as xDataset

### ISSUE THREAD

**Issue by wenlzhang** [pyrochlore/obsidian-tracker#63]
The queries are as follows:

```
searchType: fileMeta
searchTarget: cDate, size
datasetName: Date Created, Size
xDataset: 0
endDate: +1D
line:
	title: File Size Variation of All Notes
	xAxisLabel: Date Created
	yAxisLabel: Size
    fillGap: true
```

```
searchType: fileMeta
searchTarget: mDate, size
datasetName: Date Modified, Size
xDataset: 0
endDate: +1D
line:
	title: File Size Variation of All Notes
	xAxisLabel: Date Modified
	yAxisLabel: Size
    fillGap: true
```

The first figure looks correct, but I am not sure why the second figure starts from yesterday. Changing the `startDate` did not make the actual result look different. Did I miss anything in the query based on `mDate`?

The two figures are as follows:

```tracker
searchType: fileMeta
searchTarget: mDate, size
datasetName: Date Modified, Size
xDataset: 0
endDate: +1D
line:
	title: File Size Variation of All Notes
	xAxisLabel: Date Modified
	yAxisLabel: Size
    fillGap: true
```
<img width="419" alt="Screenshot 2021-09-01 at 17 37 51" src="https://user-images.githubusercontent.com/44930227/131701305-f04e50ac-6fce-46e6-b69e-28b2042ecfb3.png">
<img width="475" alt="Screenshot 2021-09-01 at 17 38 20" src="https://user-images.githubusercontent.com/44930227/131701322-c14f835f-d20f-4a1f-ad72-103346a77d0b.png">

**Comment by wenlzhang** [comment]
Thanks for the help.

I am on macOS, and I am surprised to find out that so many notes were "modified" on 2021-08-31, although I did not actually open them. This fact makes the query regarding modification date useless. 😅

I use cloud drive to sync the notes, not sure if this is related.

**Comment by pyrochlore** [comment]
I suggest using the creation date, or a field containing the date information in each note.

**Comment by wenlzhang** [comment]
> I suggest using the creation date, or a field containing the date information in each note.

This would work. I close the issue now.
