### ISSUE TITLE
Y axis value incorrect when extracting time from a table

### ISSUE THREAD

**Issue by bingguJ** [pyrochlore/obsidian-tracker#67]
Hi, I just found your plugin and I should say it's beautifully designed with a lot of features.
I am setting up a sleep time log from a table. Query used below.
```tracker
searchType: table
searchTarget: Sleep_table[0][0], Sleep_table[0][1],Sleep_table[0][2]
dateFormat: "YYYY-MM-DD"
startDate: -7d
endDate: 1d
xDataset: 0
valueShift: 00:00, -24:00, 00:00
datasetName: Date, Sleep, WakeUp
line:
    title: "Sleep"
    yAxisLocation: right
    yAxisLabel: "Time (24h)"
    lineColor: none, yellow, yellow
    showPoint: true
    showLegend: true
```
The problem is the y axis being some very large number. But when I tried the divfield example. The Y axis is in correct time such as (22:00). Any suggestion what could be wrong? 
![image](https://user-images.githubusercontent.com/66147313/132219802-90d40b1c-5abb-439f-b15b-cfa6bddbd12c.png)

Thanks

**Comment by pyrochlore** [comment]
Will do some tests on this.

**Comment by pyrochlore** [comment]
Hi, thanks for the report.
Looks like the time values collected from a table in table is not interpreted correctly.
Will fix it soon.

**Comment by pyrochlore** [comment]
Will close this issue.
More questions and suggestions are still welcome.
