### ISSUE TITLE
error: 'yAxisLabel' is not an available key  

### ISSUE THREAD

**Issue by daxmonson** [pyrochlore/obsidian-tracker#69]
Hello, 

I have some code snippets on a page I'm trying to set up Tracker work with. They look like this:

## How was Your Focus?
```tracker

searchType: tag

searchTarget: dailyquestions/focus

line:

yAxisLabel: Rating

yMin: 1

yMax: 9

```

On a daily notes template I have lines like:

 Focus today? #dailyquestions/focus: 3        

**In the page I have snippets embedded, the only text in each snippet is the following error:**

'yAxisLabel' is not an available key  

Can someone see error in the syntax or how I've set it up? Thanks

**Comment by pyrochlore** [comment]
@daxmonson yAxisLabel, yMin, yMax must be placed under the `line` key.

like this
```
…
line:
    yAxisLabel: …
    yMin: …
    yMax: …
```

**Comment by daxmonson** [comment]
Ahh yes, that was it. Appreciate that.

**Comment by pyrochlore** [comment]
Will close this issue.
More questions or suggestions are still welcome.
