### ISSUE TITLE
Tracking time values

### ISSUE THREAD

**Issue by s-kyy** [pyrochlore/obsidian-tracker#7]
This is a very interesting plugin, thanks for developing this!
I was wondering if you'd consider adding the ability to track time as a value. 
Right now I include the time I worked on something in my daily notes frontmatter like so:

```
---
clocked-in: 09:00 am
clocked-out: 05:00 pm
---
```
I'd like to visualize it with a line graph showing two lines, one for the clock-in time and one for the clock-out time. 

Maybe it would be more feasible with a 24h time format instead of a 12h time format as well as adding the unit in the Tracker code block? What do you think?

**Comment by pyrochlore** [comment]
Good idea!
With this, we can make a sleep (bedtime) tracker.
In fact, I was also thinking of a bar chart for this kind of usage showing a range between two ends, but just use a line chart could be done before that.

The input time format could be any format that matches [moment.js](https://www.tutorialspoint.com/momentjs/momentjs_format.htm), and the format on the y-axis would be in 24h for clear reading.

Now I am working on multiple targets and values (will allow multiple curves on the chart).
After that, I will definitely consider this.

**Comment by pyrochlore** [comment]
Start working on this.

**Comment by andrew8088** [comment]
Kinda related, so I'll add a comment here :)

I'm tracking sleep based on the [time tracking example](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTimeValues.md). However, the ticks on the y-axis are not at regular intervals. I'd be great if we could choose an internal of, say 1 hour, or 30 minutes, or something like that.

![Screen Shot 2021-05-13 at 5 50 37 PM](https://user-images.githubusercontent.com/115493/118192168-bc368500-b413-11eb-8c4a-64803a0e7709.png)

**Comment by pyrochlore** [comment]
Ah, I accidentally published the testing example.
That is a work in progress feature.
I will remove the example temporarily.

The suggestion about y-value interval is good. Will do.

**Comment by pyrochlore** [comment]
The feature was just released with the new version 1.6.0.
Please also check [examples](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTimeValues.md) for the usage.

**Comment by pyrochlore** [comment]
Will close the issue.
More requests and suggestions are welcome.
