### ISSUE TITLE
Date format not working properly for start/end Date

### ISSUE THREAD

**Issue by flipperyikes** [pyrochlore/obsidian-tracker#74]
I'll begin by saying I could be missing something but I'm pretty sure this is actually a bug, so, the DateFormat I'm using is "Do of MMMM Y" so the startDate and endDate  should be something like "25th of July 2021" and that works fine BUT when it's a value that ends in 1,2,3 I have to misspell for it to work so I have to write "21th of July" instead of "21st of July".

It works properly for data collection so my note named for example "23rd Of September 2021" gets put into the correct x position, it just doesn't work for end and start date.

Also since I'm already talking about dateformats, is it possible to change the date format on the x axis? I've looked at the documentation but didn't find a way to do it. Thanks.

**Comment by pyrochlore** [comment]
![image](https://user-images.githubusercontent.com/3617615/134600847-cda74230-48b4-4a73-8336-ef3afebb553d.png)
![image](https://user-images.githubusercontent.com/3617615/134600862-afa3ac1e-bb15-4350-86e7-0f2704af7950.png)

**Comment by pyrochlore** [comment]
Ah, I misunderstood your post. 
Will check the start/end date.

**Comment by flipperyikes** [comment]
After a little bit I figured out that It only doesn't work for startDates, endDates seem to work fine (I'm just sending screenshots because I probably should have sent them the first time around and just to make sure you are getting the same problem I got)

![Screenshot_1](https://user-images.githubusercontent.com/76697414/134634457-1d0a3763-885d-494f-83cd-a441260143ce.png)
using this code
![Screenshot_2](https://user-images.githubusercontent.com/76697414/134634474-18b67ac9-97b5-4aa7-9c01-2ea4a19dad76.png)
this is the result
![Screenshot_5](https://user-images.githubusercontent.com/76697414/134634495-b633f1ff-568e-408d-9b4b-b1ab0e7a2239.png)
now changing the "st" to "th"
![Screenshot_3](https://user-images.githubusercontent.com/76697414/134634541-e072d2b7-d2b0-4e3a-b047-a9c7282ceaba.png)
this is the result 
![Screenshot_4](https://user-images.githubusercontent.com/76697414/134634562-886530d8-607e-4b86-829c-5619f4817834.png)

(also of note is that the end date is using to correct "st" but still works)

Also thanks for the help with the xaxis labeling

**Comment by flipperyikes** [comment]
(the reason it says eleven dates out of range is because of the other daily notes on my vault)

**Comment by pyrochlore** [comment]
![image](https://user-images.githubusercontent.com/3617615/134666226-b60453ed-b1f6-4deb-8603-cac469626c9a.png)
Will release it soon.

**Comment by pyrochlore** [comment]
The fix was released with version 1.10.8.

**Comment by pyrochlore** [comment]
Will close this issue.
More questions or suggestions are still welcome.
