### ISSUE TITLE
Folder not readable

### ISSUE THREAD

**Issue by EhuddR** [pyrochlore/obsidian-tracker#76]
Hi! I've been using your plugin since basically it came out. It used to work really well altough this time I encountered a bug running on a Linux distro. 
This is de code I used to track a certain notes
![image](https://user-images.githubusercontent.com/78237982/135537783-86c05cc2-37e9-4bd5-90d4-82bf1b5c8c54.png)

And this is the error that I encountered, I think is related with the emojis in the folder name. There is a possible solution for this kind of issue?
![image](https://user-images.githubusercontent.com/78237982/135537973-4c053c49-c682-48bd-be95-211546d0d829.png)

Thanks in advance.

**Comment by pyrochlore** [comment]
It happened on Linux, will fix it soon.

**Comment by EhuddR** [comment]
Thank you I can't wait to see this new release

**Comment by pyrochlore** [comment]
Sorry for the long wait. 
I planned to make the next release after another issue resolved.
But If you really need this, you can download [this main.js file](https://drive.google.com/file/d/1xnDdXbwlD0IF1AJS4IJlPly-x1FvZC6k/view?usp=sharing) and replace the one in plugin folder ({your vault}/.obsidian/plugins/obsidian-tracker/main.js).
