### ISSUE TITLE
Graph not rendering

### ISSUE THREAD

**Issue by adamantski-birder** [pyrochlore/obsidian-tracker#8]
Hi, I think this plugin will be very useful. I'm using the following code:

```tracker
searchType: tag
searchTarget: dailyquestions/meditate
folder: Daily Notes
line:
yAxisLabel: Rating
yMin: 1
yMax: 9
```

Where Daily Notes is the Daily Notes folder. I am A Brit so my Date format default is DD-MM-YYYY. For some reason, the charts do not render at all when I use the above syntax. There are no error message. Am I missing something?

**Comment by pyrochlore** [comment]
Try to add a dateFormat key like this
``` tracker
searchType: tag
searchTarget: dailyquestions/meditate
folder: Daily Notes
dateFormat: DD-MM-YYYY
line:
yAxisLabel: Rating
yMin: 1
yMax: 9
```

**Comment by adamantski-birder** [comment]
Hi, Thanks for such a quick response. I've amended the code but it's still not rendering. I've also amended the dateFormat
<img width="1139" alt="Ob Plugin" src="https://user-images.githubusercontent.com/63288624/115957407-284f5880-a4fa-11eb-86d2-70432dec8040.png">
 I don't have options in the plugin settings, just the above message?

**Comment by pyrochlore** [comment]
Please update the plugin. It was just updated.

**Comment by adamantski-birder** [comment]
Aha! Thanks :( Just updated, restarted Obsidian, then deleted and reinstalled plugin, but still no joy?

**Comment by pyrochlore** [comment]
Still not works?? :(
Also note that key     
    yAxisLabel: Rating
    yMin: 1
    yMax: 9
should have an indentation.

I will make a simple test to see if there is any problems here.

**Comment by adamantski-birder** [comment]
Ah, that fixed it! Indentations. Thank you so much!

**Comment by pyrochlore** [comment]
I should add an error message for that. Thanks for the feedback.
