### ISSUE TITLE
The data for examples?

### ISSUE THREAD

**Issue by Fierce-Ninja** [pyrochlore/obsidian-tracker#80]
Hi am not too technical savvy, but trying to learn from examples you have given, which is helpful.  Trying to understand how to verify the examples.  For instance, in this example from TestExpressions.md, you say:

searchType: tag
searchTarget: meditation
folder: /diary
endDate: 2021-01-04
summary:
    template: 'Number of days having data: {{numDaysHavingData()::i}} <-- **should be 3'**

How did you get the value "3" from?  Is there some example source data file that we should load first and then practice these examples?

**Comment by pyrochlore** [comment]
I will close this issue. If the problems remain, you are welcome to reopen it.
