### ISSUE TITLE
Untitled legend for table-based charts

### ISSUE THREAD

**Issue by StanEgo** [pyrochlore/obsidian-tracker#82]
When data is taken from tables, legends are untitled. Below are screenshot for TestTable example (Obsidian 0.12.15).

![image](https://user-images.githubusercontent.com/1964984/137947675-0aeb172b-6c7b-49af-ae42-4c4509234403.png)

**Comment by pyrochlore** [comment]
I will close this issue. If the problems remain, you are welcome to reopen it.

**Comment by dionvansevenant** [comment]
> Please add this line in the code block.
> 
> ```
> ...
> xDataset: 0
> datasetName: null, data1, data2 <--- this line
> line:
> ...
> ```
> 
> The first null value is necessary as a placeholder for the x dataset.

Just getting started with this plugin, and stumbled across this issue.

The above suggestion changes `untitled0` and `untitled1` to `data1` and `data2`.

However, the column headings are `Jeffrey (kg)` and `Lucas (kg)`, which would be much more useful.

I checked the docs and a few of the other examples, and it seems `datasetName` can only be hardcoded. Is that correct?

I wondered if `datasetName` could use input like `searchTarget` does, and evaluate the column names somehow? (If not at this time, that's ok, just making sure I understand things properly)

Thanks.
