### ISSUE TITLE
Unable to read value in searchType: dvField while using symbol like euro (€)

### ISSUE THREAD

**Issue by sotostzam** [pyrochlore/obsidian-tracker#84]
When trying to read a value from a dvField that contains a symbol like euro, it is unable to read it.
For example "Bike:: 25€" returns an error "No valid Y value found in notes",
while "Bike:: 25 Euro" works just fine.

**Comment by pyrochlore** [comment]
It is caused by the unicode character not included in the search pattern.
Will fix it.

Thanks for the report.

**Comment by pyrochlore** [comment]
Unicode characters like these now can be used in `dvField` in release v1.10.9.
Will close this issue.
