### ISSUE TITLE
Null Values skipped in Line charts?

### ISSUE THREAD

**Issue by mlevison** [pyrochlore/obsidian-tracker#85]
Is there a way with Line charts to skip over null values so there is just a break in the line?

**Comment by pyrochlore** [comment]
Hi @mlevison,
The null values in the line chart won't generate points by default.
But if you still want to connect the points before and after null values, 
you can use the parameter `fillGap` to fill them up.

e.g.
``` 
...
line:
   fillGap: true
```

**Comment by mlevison** [comment]
Sorry my question wasn't clear. What I really want is the ability to have the line stop before the null value and start afresh with the next non-null value. Funny that is the default behaviour and I just wasn't seeing it. PBKAC.
