### ISSUE TITLE
Tracker no longer working in mobile (iOS)

### ISSUE THREAD

**Issue by dancemonkey** [pyrochlore/obsidian-tracker#87]
All Tracker code blocks on mobile now state "Error parsing YAML" after the latest iOS app update (on or around November 9 or so I believe). Desktop code blocks work as expected. I removed and reinstalled, no change. I've seen one other mention of this same issues yesterday on one of the Obsidian plugins Discord channel from someone with the same issue.

Since it's only on mobile not on desktop I'm assuming the issue was caused by the app update?

**Comment by pyrochlore** [comment]
Thanks for the report.
This a serious problem.
Will look into it with first priority.

**Comment by dancemonkey** [comment]
Obsidian v 1.0.5
iOS 15.1

Thanks!

**Comment by thefullmlg** [comment]
Same on desktop. Started today after Obsidian build v0.13.0. v0.13.1 from a few hours ago did not fix.

**Comment by pyrochlore** [comment]
@thefullmlg, 
I have done a quick test on Windows 10 Obsidian build 0.13.1.

Most of the examples in the example folder work as usually.
![image](https://user-images.githubusercontent.com/3617615/141409148-a73c03e1-9699-407e-8ca5-c40b85c751b4.png)

Few of them got "Error parsing YAML" and errors could be found in the console.
![image](https://user-images.githubusercontent.com/3617615/141409471-e0d3ef15-8113-4f39-bc50-993a9006215c.png)
After replace all the tabs by spaces in the md file, it works again.

It could be the parseYAML function (from Obsidian API) tightening the format check leads to this.
At the meantime we rely on the parseYAML function from Obsidian API thus we have to make sure the format is right by our own checking.

**Comment by pyrochlore** [comment]
@dancemonkey,
I just update my iPhone to 15.1 and Obsidian version 1.05.

Same situation as the previous post.
Most of the examples work. 
But if I use TAB keys instead of spaces, I will get the "Error parsing YAML" message too.

Please check the tabs in your code blocks to see if it is the problem or not.

**Comment by pyrochlore** [comment]
I will add a function to check if the input code block has any tabs before it is fed into parseYaml.

**Comment by dancemonkey** [comment]
Spaces instead of tabs did it, thank you!

**Comment by thefullmlg** [comment]
Spaces worked. thank you
