### ISSUE TITLE
Is there a way to use tags as data for a pie chart?

### ISSUE THREAD

**Issue by Hautemeal** [pyrochlore/obsidian-tracker#92]
I'm trying to track my daily moods with tags from daily notes. I would love to have a pie chart with the number of times each tag appears. If there's a way to do this with nested tags, that's even better!

E.g. #mood/happy #mood/anxious #mood/proud

If this is possible (or there's a better way), I'd greatly appreciate any help figuring out the syntax for it. 

Also, the "moods" example has a broken link.

Thanks in advance!

**Comment by ganesshkumar** [comment]
@Hautemeal, you can check moods example [here](https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTextValueMap.md). I have raised a PR for updating this broken link. Been waiting for @pyrochlore to merge this change.

**Comment by Hautemeal** [comment]
Okay, cool. thanks for the link! No idea what to do for the pie chart though?

**Comment by ganesshkumar** [comment]
@Hautemeal, try this

```tracker
searchType: tag
searchTarget: mood/happy, mood/anxious, mood/proud
pie:
    title: Pie Chart
    data: '{{sum(dataset(0))}},{{sum(dataset(1))}},{{sum(dataset(2))}}'
    dataColor: 'green,red,blue'
    label: Happy, Anxious, Proud
    ratioInnerRadius: 0.0
```

It outputs this piechart (I had 2 - happy, 1 - anxious and 1 - proud tags to produce this piechart)

![image](https://user-images.githubusercontent.com/2135089/143429116-e5ec7f25-e0bd-4b1f-babd-2e89b97539d7.png)

**Comment by ganesshkumar** [comment]
As you add more tags to the pie chart, you have to edit _searchTarget_, _data_, _dataColor_ and _label_ fields in the query!

**Comment by Hautemeal** [comment]
Ah! You're so kind and helpful! That worked. Thank you so much <3

**Comment by ganesshkumar** [comment]
Glad to be able to help you. Can we close this issue?

**Comment by pyrochlore** [comment]
Looks like this issue is resolved, will close it.
Also thanks for the help from @ganesshkumar.

**Comment by Hautemeal** [comment]
Indeed! Thanks for the help @ganesshkumar!
