### ISSUE TITLE
Skip a day from a graph

### ISSUE THREAD

**Issue by mlevison** [pyrochlore/obsidian-tracker#93]
Is there an elegant way to skip a day in a graph when there is no dailynotes file? Here is the logic - most Saturday's our family life is insanely busy. I usually don't journal etc. So no notes file. It makes my graphs harder to read because the graph is disjoint.
![Cursor_and_MarkZettelkasten_-_Obsidian_v0_12_19](https://user-images.githubusercontent.com/140902/142778163-e0883aa0-6bd8-42df-8315-0517af2f378c.jpg)

**Comment by pyrochlore** [comment]
Hi @mlevison,
Set `fillGap` to true will make all neighbor data points connected.

**Comment by pyrochlore** [comment]
Looks like it was resolved, will close this issue.
