### ISSUE TITLE
nested tags not working

### ISSUE THREAD

**Issue by wjdenny** [pyrochlore/obsidian-tracker#99]
TargetEvaluation.md states:
> Nested tags with values attached could be useful for tracking children's data separately and also still see the overall merged data using parent tags.

However, I cannot get nested tags to work. Am I doing something wrong, or is it broken?
```tracker
searchType: tag
searchTarget: '#track/project'
summary: 
	template: "{{sum()}}"
```

![image](https://user-images.githubusercontent.com/1389674/144666244-115c48c6-6a63-43ed-b5bd-9f1f5f8ffb0a.png)

**Comment by pyrochlore** [comment]
Please try
```
searchType: tag
searchTarget: track/project
summary: 
	template: "{{sum()}}"
```
No need to add a hashtag in the searchTarget.

**Comment by wjdenny** [comment]
That seems identical to the second example that I gave.

**Comment by pyrochlore** [comment]
Will do some tests on it.

**Comment by MartinMiksch** [comment]
Any updates on this? This isn't working for me either and I already tagged a lot of my daily notes with nested tags.

**Comment by pyrochlore** [comment]
Here are some tests. 
Notice the settings for 'file names containing dates' and 'file names not containing dates' are different.

![image](https://user-images.githubusercontent.com/3617615/155489925-58f58877-6320-41fe-b126-b915f47829f9.png)

![image](https://user-images.githubusercontent.com/3617615/155490369-de786510-777b-4f68-b804-d06f31437078.png)

**Comment by pyrochlore** [comment]
Will close this issue, welcome to reopen it if you still have problems with it.
